"""Generate management/rebot_b601dm/TEMP_README.md from the motor-mass audit."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(".").resolve()))
from src.simulation.rebot_b601dm.motor_mass import motor_mass_audit
from src.simulation.rebot_b601dm.racket import racket_mass_properties

BT = chr(96)
a = motor_mass_audit()
_rp = racket_mass_properties()


def code(text: str) -> str:
    return BT + text + BT


lines = [
    "# TEMP parameters: reBot B601-DM",
    "",
    "Generated by " + code("tools/generate_b601dm_temp_readme.py") + " from "
    + code("src/simulation/rebot_b601dm/motor_mass.py") + ". **Do not edit by hand.**",
    "",
    "Everything listed here is a value that is NOT real. TEMP_PARAMETERIZED_PROXY means it is a stand-in for a",
    "number that exists but was not obtained. UNKNOWN means no source was found at all. The convention follows",
    code("docs/simulation/BADMINTON_ROBOT.md:216-217") + ".",
    "",
    "---",
    "",
    "## 1. Motor masses - the largest known error in the model",
    "",
    "| Motor | Model | Modelled | Official | Ratio | Status | Source |",
    "|---|---|---|---|---|---|---|",
]
for name, r in a["rows"].items():
    modelled = "absent" if r["modelled_g"] is None else "{:.1f} g".format(r["modelled_g"])
    ratio = "-" if r["modelled_g"] is None else "{:.2f}x".format(r["ratio"])
    lines.append("| " + code(name) + " | {} | {} | {:.0f} g | {} | {} | {} |".format(
        r["model"], modelled, r["official_g"], ratio, code(r["status"]), code(r["source"])))

lines += [
    "",
    "### The size of it",
    "",
    "| | Value |",
    "|---|---|",
    "| Modelled arm mass | **{:.4f} kg** |".format(a["modelled_arm_mass_kg"]),
    "| Specified arm mass (" + code("README_zh.md:177") + ") | **{:.1f} kg** |".format(a["specified_arm_mass_kg"]),
    "| Deficit | **{:.1f} g** |".format(a["arm_deficit_g"]),
    "| Motors modelled | {:.1f} g |".format(a["modelled_motors_g"]),
    "| Motors really on the arm (3x DM4340P + 4x DM4310) | {:.1f} g |".format(a["real_motors_g"]),
    "| Motor deficit | **{:.1f} g** |".format(a["motor_deficit_g"]),
    "| Share of the arm deficit explained by the motors | **{:.0%}** |".format(a["explained_fraction"]),
    "",
    "**The model carries {:.0%} of the real arm's mass.**".format(
        a["modelled_arm_mass_kg"] / a["specified_arm_mass_kg"]),
    "",
    "### Why the official masses were NOT substituted",
    "",
    a["refusal_reason"],
    "",
    "### What would be needed to fix it",
    "",
]
for item in a["requires"]:
    lines.append("- " + item)

lines += [
    "",
    "### Which way the error points",
    "",
    a["error_direction"],
    "",
    "This matters for Task 7. A racket-head speed measured before the masses and inertias are corrected is an",
    "OVERESTIMATE, and the Task 8 plausibility gate must be read with that in mind.",
    "",
    "---",
    "",
    "## 2. Other TEMP and UNKNOWN values carried by this work",
    "",
    "| Item | Status | Why |",
    "|---|---|---|",
    "| Joint angle limits, J1-J6 | " + code("UNKNOWN") + " | No hardware document in either repository states a"
    " joint range. The URDF has values, but the URDF is simulation. Enforced in code: "
    + code("limits_for(joint, require_real=True)") + " raises. |",
    "| Gripper velocity and force | " + code("SIM_ONLY") + " / " + code("UNKNOWN") + " | The URDF declares"
    " 15 rad/s and 100 N; no hardware source exists. Left at the shipped values, never substituted. |",
    "| Motor speed and torque figures | partly real | Real per the official table, but that table documents"
    " the -2EC variants while the BOM specifies V4. Peak torques agree, so same family; V4 data not found. |",
    "| Racket mass and inertia | " + code(_rp["status"]) + " | " + _rp["source"] + ". " + _rp["note"]
    + " Needs: " + "; ".join(_rp["requires"]) + " |",
    "",
    "---",
    "",
    "## 3. Rule for using anything in this file",
    "",
    "A value tagged TEMP_PARAMETERIZED_PROXY or UNKNOWN may be used to make a model run. It may **not** be used",
    "to support a claim about what the real arm can do. When such a claim is made, the TEMP values it depended",
    "on are named in the report alongside it.",
    "",
]

out = Path("management/rebot_b601dm/TEMP_README.md")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines), encoding="utf-8")
print("wrote", out, "({} lines)".format(len(lines)))
