amp: true
batch: 8
close_mosaic: 10
copy_paste: 0.0
cos_lr: false
cutmix: 0.0
data: "E:\\\u5177\u8EAB\u667A\u80FD\\badmin_project\\runs\\shuttle_yolo26_v1\\bench_640_b8\\\
  dataset.yaml"
degrees: 5.0
device: '0'
epochs: 1
exist_ok: true
fliplr: 0.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
lr0: 0.002
mixup: 0.0
model: yolo26s-p2.yaml
mosaic: 0.2
name: bench_640_b8
nbs: 32
optimizer: auto
plots: true
pretrained: "E:\\\u5177\u8EAB\u667A\u80FD\\badmin_project\\assets\\external\\_staging\\\
  F_yolo\\weights\\yolo26s.pt"
project: "E:\\\u5177\u8EAB\u667A\u80FD\\badmin_project\\runs\\shuttle_yolo26_v1"
scale: 0.3
seed: 42
translate: 0.1
val: false
workers: 4
