"""Generate a B601-DM USD asset that enforces the REAL joint speeds.

The shipped asset declares `physxJoint:maxJointVelocity` of 2864.789 and 11459.156 deg/s. Those are the real
motors rpm figures used as rad/s: the DM4340 runs at 52.5 rpm, which is 315 deg/s, and the DM4310 at 200 rpm,
which is 1200 deg/s. The asset therefore permits 9.09x and 9.55x the real no-load speed, and any
racket-speed measurement taken on it would describe the file rather than the arm.

DESIGN CONSTRAINTS, because a patch is a place where things go wrong quietly:

1. The upstream tree is NEVER modified. It is copied, and the copy is patched.
2. Only velocity lines change. Geometry, materials and inertias are copied byte for byte, and a test asserts
   it, because a patch that silently altered wrist inertia would corrupt every later measurement in a way no
   velocity assertion would catch.
3. The gripper is left exactly as shipped. No hardware source exists for its speed, so writing a number
   there would be invention.
4. Every generated asset carries PATCH_NOTES.md naming what was replaced and what replaced it.
"""
from __future__ import annotations

import math
import shutil
from pathlib import Path

from .joint_limits import rad_s_from_rpm

# The variant is a fraction of the real no-load speed. 0.70 is the official recommendation
# (Performance_Testing_zh.md:87, "motion speed < 70% of maximum").
VARIANTS: dict[str, float] = {
    "real": 1.00,
    "recommended_70": 0.70,
}

PHYSX_REL = "payloads/Physics/physx.usda"
PHYSICS_REL = "payloads/Physics/physics.usda"

# (shipped text in physx.usda, real motor no-load rpm). 52.5 rpm -> 315 deg/s and 200 rpm -> 1200 deg/s
# exactly, because rpm * 6 is deg/s.
PHYSX_SWAPS = (("2864.789", 52.5), ("11459.156", 200.0))
PHYSICS_SWAPS = (("= 50", 52.5), ("= 200", 200.0))


def _fmt(value: float) -> str:
    """Keep 315.0 and 1200.0 recognisable while preserving precision for small numbers."""
    if abs(value - round(value)) < 1e-9:
        return "{:.1f}".format(value)
    return "{:.6g}".format(value)


def _deg_s(rpm: float) -> float:
    return rad_s_from_rpm(rpm) * 180.0 / math.pi


def _patch_physx(text: str, factor: float):
    changes = []
    for shipped, rpm in PHYSX_SWAPS:
        needle = "maxJointVelocity = " + shipped
        if needle in text:
            new = _fmt(_deg_s(rpm) * factor)
            changes.append((shipped, new))
            text = text.replace(needle, "maxJointVelocity = " + new)
    return text, changes


def _patch_physics(text: str, factor: float):
    """The custom urdf:limit:velocity metadata is in rad/s; update it to match what is now enforced."""
    changes = []
    for suffix, rpm in PHYSICS_SWAPS:
        needle = "custom float urdf:limit:velocity " + suffix
        if needle in text:
            new = _fmt(rad_s_from_rpm(rpm) * factor)
            changes.append((suffix.replace("= ", ""), new))
            text = text.replace(needle, "custom float urdf:limit:velocity = " + new)
    return text, changes


NOTES_TEMPLATE = """# Patch notes: real joint velocity limits

Generated by `src/simulation/rebot_b601dm/patch_asset.py`, variant **{variant}** (factor {factor} on the real
no-load speeds).

The upstream tree was copied, not modified. Only velocity lines differ from it.

## Why

The shipped asset enforced joint speeds 9.09x and 9.55x the real motors, because the real rpm figures were
used as rad/s. The DM4340 runs at 52.5 rpm, which is 315 deg/s, and the DM4310 at 200 rpm, which is
1200 deg/s.

## What changed

{changes}
## What deliberately did NOT change

- The gripper joint velocities stay at the shipped 859.4367 deg/s. No hardware source exists for the gripper
  speed, so writing a value there would be invention.
- Geometry, materials, masses and inertias are copied byte for byte, and a test asserts it.

## Caveat carried forward

The official motor table documents the `-2EC` variants while the BOM specifies `DM4340P(V4)` and
`DM4310(V4)`. Peak torques agree at 27 and 7 N m, which says same family; V4-specific speed data was not
found. See `management/rebot_b601dm/REBOT_B601DM_REPORT.md`.
"""


def patch_asset(source_dir, out_dir, *, variant: str = "real") -> Path:
    """Copy the asset tree and replace only its joint velocity limits. Returns the patched tree root."""
    if variant not in VARIANTS:
        raise ValueError(
            "unknown variant " + repr(variant) + "; expected one of " + ", ".join(sorted(VARIANTS))
        )
    factor = VARIANTS[variant]
    source = Path(source_dir)
    out = Path(out_dir)
    if not source.is_dir():
        raise FileNotFoundError("asset tree not found: " + str(source))
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(source, out)

    per_file = {}
    physx = out / PHYSX_REL
    text, changes = _patch_physx(physx.read_text(encoding="utf-8"), factor)
    physx.write_text(text, encoding="utf-8")
    per_file[PHYSX_REL] = changes

    physics = out / PHYSICS_REL
    if physics.is_file():
        text, changes = _patch_physics(physics.read_text(encoding="utf-8"), factor)
        physics.write_text(text, encoding="utf-8")
        per_file[PHYSICS_REL] = changes

    lines = []
    for rel, changes in per_file.items():
        lines.append("- `" + rel + "`:")
        if not changes:
            lines.append("  - nothing matched; the file may already have been patched")
        for old, new in changes:
            lines.append("  - `" + old + "` becomes `" + new + "`")
    (out / "PATCH_NOTES.md").write_text(
        NOTES_TEMPLATE.format(variant=variant, factor=_fmt(factor), changes="\n".join(lines) + "\n"),
        encoding="utf-8",
    )
    return out