# -*- coding: utf-8 -*-
"""T10 online adaptation tests (plan docs/superpowers/plans/2026-09-13-brain-modules.md, row T10).

Contract under test (src/badminton_brain/adaptation/online_adaptation.py):
  * consumes (Feedback, UnifiedState), returns a correction dict (AdaptationModule.output_type);
  * prediction error e = predicted - measured drives a bounded (normalized LMS / Gauss-Newton)
    update of slow parameters drag_scale / wind / delay;
  * every estimate is clamped into declared bounds, per-step increments are capped;
  * a residual ledger keeps the last K prediction errors per environment;
  * reset(env_ids) clears only the selected environments.

The convergence tests do not re-use the module's own update algebra: the residual fed back is
generated by the real quadratic-drag model in src/trajectory/shuttle_aerodynamics.py.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'src'))
sys.path.insert(0, str(ROOT / 'src' / 'trajectory'))

from shuttle_aerodynamics import acceleration, k_from_aerodynamic_length  # noqa: E402

from badminton_brain.adaptation.online_adaptation import OnlineAdaptation  # noqa: E402
from badminton_brain.interfaces import AdaptationModule, interface_layer_of  # noqa: E402
from badminton_brain.types import BrainBoundaryError, Feedback, Layer, UnifiedState  # noqa: E402

K_BASE = k_from_aerodynamic_length(6.5)          # literature feather shuttle L = 6.5 m
GRAVITY = np.array([0.0, 0.0, -9.80665])
DT = 0.2                                          # prediction interval used by every test


def make_state(position, velocity, timestamp: float) -> UnifiedState:
    n = np.asarray(velocity, dtype=float).shape[0]
    return UnifiedState(
        base_pose=np.tile(np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]), (n, 1)),
        base_twist=np.zeros((n, 6)),
        joint_pos=np.zeros((n, 6)),
        joint_vel=np.zeros((n, 6)),
        racket_contact_pose=np.tile(np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]), (n, 1)),
        racket_contact_twist=np.zeros((n, 6)),
        shuttle_position=np.asarray(position, dtype=float),
        shuttle_velocity=np.asarray(velocity, dtype=float),
        timestamp=timestamp)


def position_residual(position, velocity, *, pred_k, pred_wind, true_k, true_wind) -> np.ndarray:
    """predicted - measured position after DT, both from the real drag model (single env)."""
    p = np.asarray(position, dtype=float)[0]
    v = np.asarray(velocity, dtype=float)[0]
    a_pred = acceleration(p, v, k_per_m=pred_k, gravity=GRAVITY,
                          wind=np.asarray(pred_wind, dtype=float).reshape(-1)[:3])
    a_true = acceleration(p, v, k_per_m=true_k, gravity=GRAVITY,
                          wind=np.asarray(true_wind, dtype=float).reshape(-1)[:3])
    p_pred = p + v * DT + 0.5 * a_pred * DT ** 2
    p_obs = p + v * DT + 0.5 * a_true * DT ** 2
    return (p_pred - p_obs)[None, :]


def orbit_velocity(step: int, speed: float = 4.0) -> np.ndarray:
    """Deterministic changing velocity direction so the residual is not a single fixed axis."""
    theta = 0.05 * step
    return np.array([[speed * np.cos(theta), speed * np.sin(theta), -0.5]])


class LayerContractTests(unittest.TestCase):
    def test_module_binds_to_the_adaptation_layer(self) -> None:
        module = OnlineAdaptation(num_envs=2)
        self.assertIsInstance(module, AdaptationModule)
        self.assertIs(interface_layer_of(module), Layer.ADAPTATION)
        self.assertEqual(module.layer, Layer.ADAPTATION)

    def test_process_returns_the_correction_dict(self) -> None:
        module = OnlineAdaptation(num_envs=2)
        state = make_state(np.zeros((2, 3)), orbit_velocity(0).repeat(2, axis=0), 0.0)
        out = module.process(Feedback(prediction_error=np.zeros((2, 3)), timestamp=DT), state)
        self.assertIsInstance(out, dict)
        for key in ('drag_scale', 'wind', 'delay_s', 'residual', 'updates'):
            self.assertIn(key, out)
        self.assertEqual(out['drag_scale'].shape, (2,))
        self.assertEqual(out['wind'].shape, (2, 3))
        self.assertEqual(out['delay_s'].shape, (2,))


class ConvergenceTests(unittest.TestCase):
    """Systematic bias -> slow estimate converges to the true value."""

    def test_drag_scale_converges_to_truth(self) -> None:
        true_scale = 1.25
        module = OnlineAdaptation(num_envs=1, estimate=('drag_scale',))
        position = np.array([[0.0, 0.0, 3.0]])
        errors = []
        for step in range(60):
            velocity = orbit_velocity(step)
            t0 = step * DT
            residual = position_residual(
                position, velocity,
                pred_k=K_BASE * float(module.drag_scale[0]), pred_wind=np.zeros(3),
                true_k=K_BASE * true_scale, true_wind=np.zeros(3))
            errors.append(abs(float(module.drag_scale[0]) - true_scale))
            module.process(Feedback(prediction_error=residual, timestamp=t0 + DT),
                           make_state(position, velocity, t0))
        final = abs(float(module.drag_scale[0]) - true_scale)
        self.assertLess(final, 1e-6, 'drag scale did not converge: %r' % module.drag_scale[0])
        self.assertLess(final, errors[0] / 1e3, 'convergence was not monotone enough')
        for before, after in zip(errors[:20], errors[1:21]):
            self.assertLessEqual(after, before + 1e-12)

    def test_wind_estimate_converges_to_truth(self) -> None:
        true_wind = np.array([0.6, -0.4, 0.0])
        module = OnlineAdaptation(num_envs=1, estimate=('wind',))
        position = np.array([[0.0, 0.0, 3.0]])
        errors = []
        for step in range(60):
            velocity = orbit_velocity(step)
            t0 = step * DT
            residual = position_residual(
                position, velocity,
                pred_k=K_BASE, pred_wind=module.wind[0],
                true_k=K_BASE, true_wind=true_wind)
            errors.append(float(np.abs(module.wind[0] - true_wind).max()))
            module.process(Feedback(prediction_error=residual, timestamp=t0 + DT),
                           make_state(position, velocity, t0))
        # measured: 6.0e-1 (initial) -> 6.9e-3 after 20 samples -> 9.2e-7 after 60 samples
        np.testing.assert_allclose(module.wind[0], true_wind, atol=1e-3)
        self.assertLess(errors[0], 0.8)
        self.assertLess(errors[19], 1e-2, 'wind did not converge within 20 samples')

    def test_delay_estimate_converges_to_truth(self) -> None:
        true_delay = 0.02
        module = OnlineAdaptation(num_envs=1, estimate=('delay',))
        position = np.array([[0.0, 0.0, 3.0]])
        for step in range(60):
            velocity = orbit_velocity(step)
            t0 = step * DT
            # the predictor assumed the shuttle state is delay seconds older than reality
            residual = -velocity * (float(module.delay_s[0]) - true_delay)
            module.process(Feedback(prediction_error=residual, timestamp=t0 + DT),
                           make_state(position, velocity, t0))
        self.assertAlmostEqual(float(module.delay_s[0]), true_delay, places=6)


class BoundedUpdateTests(unittest.TestCase):
    def test_estimates_stay_inside_bounds_and_steps_are_capped(self) -> None:
        module = OnlineAdaptation(
            num_envs=1,
            estimate=('drag_scale', 'wind', 'delay'),
            drag_scale_bounds=(0.5, 2.0),
            wind_bounds_mps=(-1.0, 1.0),
            delay_bounds_s=(-0.02, 0.02),
            max_step_drag_scale=0.05,
            max_step_wind_mps=0.1,
            max_step_delay_s=0.001)
        position = np.array([[0.0, 0.0, 3.0]])
        velocity = orbit_velocity(0)
        previous = np.array([1.0, 0.0, 0.0, 0.0, 0.0])
        limited_seen = False
        out = None
        for step in range(400):
            out = module.process(Feedback(prediction_error=np.array([[1.0, 0.5, -0.4]]),
                                          timestamp=step * DT + DT),
                                 make_state(position, velocity, step * DT))
            now = np.array([out['drag_scale'][0], out['wind'][0, 0], out['wind'][0, 1],
                            out['wind'][0, 2], out['delay_s'][0]])
            step_size = np.abs(now - previous)
            self.assertLessEqual(step_size[0], 0.05 + 1e-12)
            self.assertLessEqual(step_size[1:4].max(), 0.1 + 1e-12)
            self.assertLessEqual(step_size[4], 0.001 + 1e-12)
            self.assertLessEqual(now[0], 2.0 + 1e-12)
            self.assertGreaterEqual(now[0], 0.5 - 1e-12)
            self.assertLessEqual(np.abs(now[1:4]).max(), 1.0 + 1e-12)
            self.assertLessEqual(abs(now[4]), 0.02 + 1e-12)
            self.assertTrue(np.all(np.isfinite(now)))
            limited_seen = limited_seen or bool(out['limited'][0])
            previous = now
        self.assertTrue(limited_seen, 'the per-step cap never engaged')
        self.assertTrue(bool(out['clamped'][0]), 'no bound was reported as engaged')
        self.assertAlmostEqual(float(module.drag_scale[0]), 2.0, places=9)
        self.assertAlmostEqual(float(module.delay_s[0]), 0.02, places=9)

    def test_nonfinite_error_is_ignored_and_keeps_state_finite(self) -> None:
        module = OnlineAdaptation(num_envs=2, estimate=('drag_scale',))
        position = np.zeros((2, 3)) + np.array([0.0, 0.0, 3.0])
        velocity = orbit_velocity(0).repeat(2, axis=0)
        bad = np.array([[np.nan, 0.0, 0.0], [0.2, 0.0, 0.0]])
        out = module.process(Feedback(prediction_error=bad, timestamp=DT),
                             make_state(position, velocity, 0.0))
        self.assertAlmostEqual(float(module.drag_scale[0]), 1.0, places=12)
        self.assertNotAlmostEqual(float(module.drag_scale[1]), 1.0)
        self.assertTrue(np.all(np.isfinite(module.drag_scale)))
        self.assertTrue(np.isnan(out['residual'][0]))
        self.assertTrue(out['updated'][1])
        self.assertEqual(int(module.residual_counts()[0]), 0)
        self.assertEqual(int(module.residual_counts()[1]), 1)

    def test_random_large_errors_never_diverge(self) -> None:
        rng = np.random.default_rng(20260913)
        module = OnlineAdaptation(num_envs=4, estimate=('drag_scale', 'wind', 'delay'),
                                  ledger_size=8)
        position = np.zeros((4, 3)) + np.array([0.0, 0.0, 3.0])
        velocity = np.tile(np.array([[4.0, 1.0, -0.5]]), (4, 1))
        for step in range(500):
            error = rng.normal(scale=25.0, size=(4, 3))     # metres of nonsense
            out = module.process(Feedback(prediction_error=error, timestamp=step * DT + DT),
                                 make_state(position, velocity, step * DT))
            self.assertTrue(np.all(np.isfinite(out['drag_scale'])))
            self.assertTrue(np.all(np.isfinite(out['wind'])))
            self.assertTrue(np.all(np.isfinite(out['delay_s'])))
        self.assertTrue(np.all(module.drag_scale >= module.drag_scale_bounds[0] - 1e-12))
        self.assertTrue(np.all(module.drag_scale <= module.drag_scale_bounds[1] + 1e-12))
        self.assertTrue(np.all(module.wind >= module.wind_bounds_mps[0] - 1e-12))
        self.assertTrue(np.all(module.wind <= module.wind_bounds_mps[1] + 1e-12))
        self.assertTrue(np.all(np.abs(module.delay_s) <= module.delay_bounds_s[1] + 1e-12))
        np.testing.assert_array_equal(module.residual_counts(), [8, 8, 8, 8])
        self.assertTrue(np.all(module.residual_norms() >= 0.0))
        self.assertTrue(np.all(np.isfinite(module.residual_mean())))

    def test_mismatched_batch_and_wrong_types_raise(self) -> None:
        module = OnlineAdaptation(num_envs=2)
        state = make_state(np.zeros((2, 3)), orbit_velocity(0).repeat(2, axis=0), 0.0)
        with self.assertRaises(BrainBoundaryError):
            module.process(Feedback(prediction_error=np.zeros((3, 3)), timestamp=DT), state)
        with self.assertRaises(BrainBoundaryError):
            module.process(Feedback(prediction_error=np.zeros((2, 3)), timestamp=DT),
                           make_state(np.zeros((3, 3)), orbit_velocity(0).repeat(3, axis=0), 0.0))
        with self.assertRaises(BrainBoundaryError):
            module.process(object(), state)


class LedgerTests(unittest.TestCase):
    def test_ledger_keeps_the_last_k_errors_per_env(self) -> None:
        window = 4
        module = OnlineAdaptation(num_envs=2, estimate=('drag_scale',), ledger_size=window)
        position = np.zeros((2, 3)) + np.array([0.0, 0.0, 3.0])
        velocity = orbit_velocity(0).repeat(2, axis=0)
        pushed = []
        for step in range(6):
            error = np.zeros((2, 3))
            error[0, 0] = 0.1 * (step + 1)
            error[1, 0] = -0.2 * (step + 1)
            pushed.append(error.copy())
            module.process(Feedback(prediction_error=error, timestamp=step * DT + DT),
                           make_state(position, velocity, step * DT))
        ledger = module.residual_ledger()
        self.assertEqual(ledger.shape, (2, window, 3))
        np.testing.assert_allclose(ledger[0, :, 0], [0.3, 0.4, 0.5, 0.6])
        np.testing.assert_allclose(ledger[1, :, 0], [-0.6, -0.8, -1.0, -1.2])
        np.testing.assert_allclose(ledger[0], np.asarray(pushed[-window:])[:, 0])
        norms = module.residual_norms()
        np.testing.assert_allclose(norms[0], [0.3, 0.4, 0.5, 0.6])
        np.testing.assert_allclose(module.residual_mean(), [0.45, 0.9], atol=1e-12)
        np.testing.assert_array_equal(module.residual_counts(), [window, window])

    def test_ledger_is_nan_padded_before_it_is_full(self) -> None:
        module = OnlineAdaptation(num_envs=1, estimate=('drag_scale',), ledger_size=3)
        position = np.array([[0.0, 0.0, 3.0]])
        velocity = orbit_velocity(0)
        error = np.array([[0.5, 0.0, 0.0]])
        module.process(Feedback(prediction_error=error, timestamp=DT),
                       make_state(position, velocity, 0.0))
        ledger = module.residual_ledger()
        np.testing.assert_allclose(ledger[0, -1], error[0])
        self.assertTrue(np.all(np.isnan(ledger[0, :-1])))
        self.assertEqual(int(module.residual_counts()[0]), 1)

    def test_scalar_error_is_interpreted_along_the_shuttle_velocity(self) -> None:
        module = OnlineAdaptation(num_envs=1, estimate=('drag_scale',), ledger_size=2)
        position = np.array([[0.0, 0.0, 3.0]])
        velocity = np.array([[3.0, 4.0, 0.0]])
        module.process(Feedback(prediction_error=np.array([2.0]), timestamp=DT),
                       make_state(position, velocity, 0.0))
        np.testing.assert_allclose(module.residual_ledger()[0, -1], [1.2, 1.6, 0.0], atol=1e-12)

    def test_missing_error_does_not_update_but_is_reported(self) -> None:
        module = OnlineAdaptation(num_envs=1, estimate=('drag_scale',))
        state = make_state(np.array([[0.0, 0.0, 3.0]]), orbit_velocity(0), 0.0)
        out = module.process(Feedback(prediction_error=None, timestamp=DT), state)
        self.assertFalse(bool(out['updated'][0]))
        self.assertTrue(np.isnan(out['residual'][0]))
        self.assertAlmostEqual(float(module.drag_scale[0]), 1.0, places=12)
        self.assertEqual(int(module.residual_counts()[0]), 0)


class ResetTests(unittest.TestCase):
    def test_reset_clears_only_the_selected_envs(self) -> None:
        module = OnlineAdaptation(num_envs=3, estimate=('drag_scale', 'wind', 'delay'),
                                  ledger_size=4)
        position = np.zeros((3, 3)) + np.array([0.0, 0.0, 3.0])
        velocity = orbit_velocity(0).repeat(3, axis=0)
        for step in range(5):
            error = np.array([[0.3 * (step + 1), 0.0, 0.0],
                              [0.6 * (step + 1), 0.0, 0.0],
                              [-0.2 * (step + 1), 0.0, 0.0]])
            module.process(Feedback(prediction_error=error, timestamp=step * DT + DT),
                           make_state(position, velocity, step * DT))
        self.assertNotAlmostEqual(float(module.drag_scale[0]), 1.0, places=6)
        self.assertNotAlmostEqual(float(module.drag_scale[1]), 1.0, places=6)
        drag_before = module.drag_scale.copy()
        wind_before = module.wind.copy()
        delay_before = module.delay_s.copy()
        counts_before = module.residual_counts().copy()
        updates_before = module.updates.copy()

        module.reset([0])

        np.testing.assert_allclose(module.drag_scale[0], 1.0)
        np.testing.assert_allclose(module.wind[0], np.zeros(3))
        np.testing.assert_allclose(module.delay_s[0], 0.0)
        self.assertEqual(int(module.residual_counts()[0]), 0)
        self.assertEqual(int(module.updates[0]), 0)
        self.assertTrue(np.all(np.isnan(module.residual_ledger()[0])))

        np.testing.assert_allclose(module.drag_scale[1:], drag_before[1:])
        np.testing.assert_allclose(module.wind[1:], wind_before[1:])
        np.testing.assert_allclose(module.delay_s[1:], delay_before[1:])
        np.testing.assert_array_equal(module.residual_counts()[1:], counts_before[1:])
        np.testing.assert_array_equal(module.updates[1:], updates_before[1:])

        module.reset(np.array([2]))
        np.testing.assert_allclose(module.drag_scale[2], 1.0)
        np.testing.assert_allclose(module.drag_scale[1], drag_before[1])

    def test_reset_rejects_out_of_range_ids(self) -> None:
        module = OnlineAdaptation(num_envs=2)
        with self.assertRaises(BrainBoundaryError):
            module.reset([5])


if __name__ == '__main__':
    unittest.main(verbosity=2)
