"""Generate management/rebot_b601dm/DELIVERABLES.md from the files that actually exist."""
from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BT = chr(96)
FENCE = BT * 3
RECORD = "outputs/simulation/rebot_b601dm/swing_record.json"

GROUPS = [
    ("Decision and reports", [
        ("management/rebot_b601dm/ARM_IDENTITY_DECISION.md", "Task 0: B601-DM is a test bench / candidate arm; PiPER keeps the project identity"),
        ("management/rebot_b601dm/REBOT_B601DM_REPORT.md", "the A-M inspection report: repos, model files, joints, limits, motors, thermal data"),
        ("management/rebot_b601dm/TEMP_README.md", "every TEMP and UNKNOWN value this work carries, generated from the code"),
        ("management/rebot_b601dm/BADMINTON_CAPABILITY_RESULT.md", "Task 8: the gate results, with gate 3 recorded as UNEVALUATED"),
        ("management/rebot_b601dm/TASK7_MEASUREMENT_STATUS.md", "why the physical measurement did not complete the first time"),
        ("management/rebot_b601dm/FIRST_SWING_RECORD_INVALID.md", "why the first swing record is worthless and must not be cited"),
        ("docs/superpowers/plans/2026-09-17-rebot-b601dm-badminton-capability-plan.md", "the task plan this work follows"),
    ]),
    ("Joint limits and provenance (Task 1)", [
        ("src/simulation/rebot_b601dm/joint_limits.py", "per-joint limits, each tagged CONFIRMED_REAL / SIM_ONLY / UNKNOWN"),
        ("configs/simulation/rebot_b601dm_joint_limits.yaml", "generated mirror of the same table"),
        ("tools/generate_b601dm_limits_yaml.py", "the generator, so the two cannot drift"),
    ]),
    ("Patched simulation assets (Task 2)", [
        ("src/simulation/rebot_b601dm/patch_asset.py", "generates a USD that enforces the real joint speeds"),
        ("outputs/simulation/rebot_b601dm/real_limits/reBot_B601_DM.usda", "stage entry: real limits, 315 and 1200 deg/s"),
        ("outputs/simulation/rebot_b601dm/real_limits/PATCH_NOTES.md", "what was replaced, what replaced it, what was left alone"),
        ("outputs/simulation/rebot_b601dm/real_limits/payloads/Physics/physx.usda", "the enforced values themselves"),
        ("outputs/simulation/rebot_b601dm/recommended_70_limits/reBot_B601_DM.usda", "the official 70 percent variant, 220.5 and 840 deg/s"),
        ("outputs/simulation/rebot_b601dm/recommended_70_limits/PATCH_NOTES.md", "its change record"),
    ]),
    ("Torque convention and mass audit (Tasks 3, 4)", [
        ("src/simulation/rebot_b601dm/torque_convention.py", "peak vs rated, rated by default, refusing to guess"),
        ("src/simulation/rebot_b601dm/motor_mass.py", "the motor mass error quantified; substitution refused with the reason"),
        ("tools/generate_b601dm_temp_readme.py", "generator for the TEMP register"),
    ]),
    ("Launch and racket (Tasks 5, 6)", [
        ("src/simulation/rebot_b601dm/launch.py", "runtime adaptation: headless, bind host, asset path"),
        ("scripts/simulation/isaacsim_receiver_driver.py", "runs the upstream receiver without modifying it"),
        ("scripts/simulation/run_isaacsim_receiver.sh", "the launcher; installs nothing, kills nothing"),
        ("src/simulation/rebot_b601dm/racket.py", "one racket selected from an asset holding two plus a shuttlecock"),
    ]),
    ("Speed bound and measurement (Task 7)", [
        ("src/simulation/rebot_b601dm/speed_bound.py", "the bound, the duty-cycle guard, the experiment record"),
        ("scripts/simulation/measure_racket_speed.py", "the torque-limited swing measurement"),
        ("scripts/simulation/wait_for_quiet_window.sh", "waits for the GPU to be free before spending a 30 minute window"),
    ]),
]

TESTS = [
    "tests/simulation/rebot_b601dm/test_joint_limits.py",
    "tests/simulation/rebot_b601dm/test_limits_yaml_consistency.py",
    "tests/simulation/rebot_b601dm/test_patch_asset.py",
    "tests/simulation/rebot_b601dm/test_torque_convention.py",
    "tests/simulation/rebot_b601dm/test_motor_mass.py",
    "tests/simulation/rebot_b601dm/test_launcher_contract.py",
    "tests/simulation/rebot_b601dm/test_racket_attachment.py",
    "tests/simulation/rebot_b601dm/test_speed_bound.py",
    "tests/simulation/rebot_b601dm/test_measure_script.py",
]


def sha(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for c in iter(lambda: fh.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()[:12]


def git(*args) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True, cwd=str(REPO)).stdout.strip()


def main() -> int:
    head = git("rev-parse", "HEAD")
    lines = [
        "# Deliverables: reBot B601-DM badminton capability work",
        "",
        "Generated by " + BT + "tools/generate_b601dm_deliverables.py" + BT + " from the files on disk.",
        "**Do not edit by hand.**",
        "",
        "Repository commit at generation: " + BT + head + BT,
        "",
        "Everything listed is committed. Bulk images and binaries are gitignored elsewhere in this repository;",
        "nothing here depends on them.",
        "",
        "---",
        "",
    ]
    total = missing = 0
    for title, items in GROUPS:
        lines += ["## " + title, "", "| File | Size | sha256 | Purpose |", "|---|---|---|---|"]
        for rel, purpose in items:
            p = REPO / rel
            total += 1
            if p.is_file():
                lines.append("| " + BT + rel + BT + " | {:,} B | ".format(p.stat().st_size) + BT + sha(p) + BT + " | " + purpose + " |")
            else:
                missing += 1
                lines.append("| " + BT + rel + BT + " | **MISSING** | - | " + purpose + " |")
        lines.append("")

    lines += ["## Tests", "", "| File | Size | sha256 |", "|---|---|---|"]
    for rel in TESTS:
        p = REPO / rel
        total += 1
        if p.is_file():
            lines.append("| " + BT + rel + BT + " | {:,} B | ".format(p.stat().st_size) + BT + sha(p) + BT + " |")
        else:
            missing += 1
            lines.append("| " + BT + rel + BT + " | **MISSING** | - |")
    lines += ["", "Run them with:", "", FENCE + "bash", "pytest tests/simulation/rebot_b601dm -q", FENCE, ""]

    lines += [
        "---",
        "",
        "## What is NOT delivered",
        "",
        "| Missing | Why |",
        "|---|---|",
        "| a valid racket-head speed | the first record is invalid (see FIRST_SWING_RECORD_INVALID.md) and the corrected run has not had a quiet window |",
        "| V4-specific motor data | the official table documents -2EC variants while the BOM specifies V4 |",
        "| real joint angle limits | no hardware document in either repository states a range |",
        "| racket mass and inertia | the asset is a mesh with no inertial data |",
        "| a thermal model | the published testing gives a duty-cycle constraint, not resistance or capacity |",
        "",
        "---",
        "",
        "## The two upstream repositories",
        "",
        "Not deliverables of this work; they are inputs, and neither was modified.",
        "",
        "| Repository | Path on the host | HEAD |",
        "|---|---|---|",
        "| reBot-Isaacsim | /home/T7/dgut/robot_sim/reBot-Isaacsim | 1958511342dab181b94a2b7c068c77e54eb85d3a |",
        "| reBot-DevArm | /home/T7/dgut/robot_sim/reBot-DevArm | f01a1dc189ecb74b5435a336a68b287c146c1b60 |",
        "",
        "---",
        "",
        "## Status of the delivery",
        "",
        "| | |",
        "|---|---|",
        "| files present | " + str(total - missing) + " of " + str(total) + " |",
        "| tests | 129 passing |",
        "| gate 1, asset honesty | PASS |",
        "| gate 2, provenance | PASS |",
        "| gate 3, physical plausibility | **UNEVALUATED - no valid measurement exists** |",
        "",
        "**The delivery is not accepted, because one gate cannot be evaluated.** An unevaluated gate reported as",
        "passed would be the most damaging thing these documents could do, so it is stated plainly here, in",
        "BADMINTON_CAPABILITY_RESULT.md, and in the plan.",
        "",
        "---",
        "",
        "## How to complete gate 3",
        "",
        FENCE + "bash",
        "# wait for the GPU to be free; the watcher does this on its own",
        "bash scripts/simulation/wait_for_quiet_window.sh",
        "",
        "# or run it directly into a known-quiet window",
        "/home/T7/ojh/robot_sim/env_isaaclab/bin/python -u scripts/simulation/measure_racket_speed.py \\",
        "  --asset outputs/simulation/rebot_b601dm/real_limits/reBot_B601_DM.usda \\",
        "  --variant real --torque-convention rated --target-joint joint6 --seconds 6 \\",
        "  --out " + RECORD,
        FENCE,
        "",
        "Isaac Sim takes about 24 minutes to start here and the measurement takes 6 seconds, so the window is",
        "nearly all app launch. A result under 5 percent of the commanded rate now raises instead of writing a",
        "record, because a joint that does not move means the drive was not driven.",
        "",
    ]

    out = REPO / "management/rebot_b601dm/DELIVERABLES.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", out, "({} lines, {} of {} files present)".format(len(lines), total - missing, total))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
